In [31]:
import torch

obs_data = torch.rand(8, 3)  # Random tensor of shape [136, 3]
v = obs_data[None, :, :, None].detach()

In [32]:
v = v.permute(0, 3, 1, 2)
v.shape

torch.Size([1, 1, 8, 3])

In [33]:
v[0][0]

tensor([[0.0142, 0.1671, 0.6769],
        [0.1526, 0.3822, 0.9765],
        [0.0939, 0.7863, 0.6377],
        [0.8530, 0.9523, 0.9712],
        [0.4906, 0.8465, 0.0606],
        [0.9110, 0.3630, 0.5717],
        [0.7558, 0.1802, 0.0386],
        [0.8728, 0.2853, 0.2821]])

In [34]:
obs_data

tensor([[0.0142, 0.1671, 0.6769],
        [0.1526, 0.3822, 0.9765],
        [0.0939, 0.7863, 0.6377],
        [0.8530, 0.9523, 0.9712],
        [0.4906, 0.8465, 0.0606],
        [0.9110, 0.3630, 0.5717],
        [0.7558, 0.1802, 0.0386],
        [0.8728, 0.2853, 0.2821]])

In [35]:
v = v.permute(0, 3, 1, 2)
v.shape , v


(torch.Size([1, 3, 1, 8]),
 tensor([[[[0.0142, 0.1526, 0.0939, 0.8530, 0.4906, 0.9110, 0.7558, 0.8728]],
 
          [[0.1671, 0.3822, 0.7863, 0.9523, 0.8465, 0.3630, 0.1802, 0.2853]],
 
          [[0.6769, 0.9765, 0.6377, 0.9712, 0.0606, 0.5717, 0.0386, 0.2821]]]]))

In [36]:
n_ped = v.size(-1)
n_ped

8

In [37]:
temp = v.permute(0, 2, 3, 1).unsqueeze(dim=-2).repeat_interleave(repeats=n_ped, dim=-2)
temp

tensor([[[[[0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769],
           [0.0142, 0.1671, 0.6769]],

          [[0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765],
           [0.1526, 0.3822, 0.9765]],

          [[0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377],
           [0.0939, 0.7863, 0.6377]],

          [[0.8530, 0.9523, 0.9712],
           [0.8530, 0.9523, 0.9712],
           [0.8530, 0.9523, 0.97

In [38]:
temp.shape  ,temp

(torch.Size([1, 1, 8, 8, 3]),
 tensor([[[[[0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769],
            [0.0142, 0.1671, 0.6769]],
 
           [[0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765],
            [0.1526, 0.3822, 0.9765]],
 
           [[0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377],
            [0.0939, 0.7863, 0.6377]],
 
           [[0.8530, 0.9523, 0.9712],
           

In [39]:
a = (temp - temp.transpose(2, 3)).norm(p=2, dim=-1)

In [40]:
a

tensor([[[[0.0000, 0.3939, 0.6255, 1.1860, 1.0337, 0.9240, 0.9785, 0.9524],
          [0.3939, 0.0000, 0.5306, 0.9031, 1.0811, 0.8599, 1.1333, 1.0051],
          [0.6255, 0.5306, 0.0000, 0.8456, 0.7030, 0.9227, 1.0791, 0.9921],
          [1.1860, 0.9031, 0.8456, 0.0000, 0.9858, 0.7143, 1.2146, 0.9591],
          [1.0337, 1.0811, 0.7030, 0.9858, 0.0000, 0.8196, 0.7175, 0.7142],
          [0.9240, 0.8599, 0.9227, 0.7143, 0.8196, 0.0000, 0.5846, 0.3022],
          [0.9785, 1.1333, 1.0791, 1.2146, 0.7175, 0.5846, 0.0000, 0.2899],
          [0.9524, 1.0051, 0.9921, 0.9591, 0.7142, 0.3022, 0.2899, 0.0000]]]])

In [41]:
a_inv = 1. / a

In [42]:
a_inv[a == 0] = 0

In [43]:
a_inv

tensor([[[[0.0000, 2.5384, 1.5986, 0.8432, 0.9674, 1.0822, 1.0219, 1.0500],
          [2.5384, 0.0000, 1.8847, 1.1073, 0.9250, 1.1629, 0.8824, 0.9949],
          [1.5986, 1.8847, 0.0000, 1.1826, 1.4225, 1.0838, 0.9267, 1.0080],
          [0.8432, 1.1073, 1.1826, 0.0000, 1.0144, 1.4000, 0.8233, 1.0426],
          [0.9674, 0.9250, 1.4225, 1.0144, 0.0000, 1.2201, 1.3938, 1.4002],
          [1.0822, 1.1629, 1.0838, 1.4000, 1.2201, 0.0000, 1.7106, 3.3087],
          [1.0219, 0.8824, 0.9267, 0.8233, 1.3938, 1.7106, 0.0000, 3.4489],
          [1.0500, 0.9949, 1.0080, 1.0426, 1.4002, 3.3087, 3.4489, 0.0000]]]])

In [44]:
a_hat = a_inv + torch.eye(n=n_ped, device=v.device)

In [45]:
node_degrees = a_hat.sum(dim=-1).unsqueeze(dim=-1)
degs_inv_sqrt = torch.pow(node_degrees, -0.5)
degs_inv_sqrt[torch.isinf(degs_inv_sqrt)] = 0
norm_degs_matrix = torch.eye(n=n_ped, device=v.device) * degs_inv_sqrt

In [46]:
a = torch.eye(n=n_ped, device=v.device) - norm_degs_matrix @ a_hat @ norm_degs_matrix

In [47]:
a = a.squeeze(dim=0).detach()

In [48]:
a.shape

torch.Size([1, 8, 8])

In [49]:
a = torch.rand((8,3,3))

In [52]:
a.size(0)

8

In [53]:
import torch

# Create tensors with the given shapes
x = torch.randn(1, 8, 20, 8, 3)
A = torch.randn(8, 3, 3)

# Perform the einsum operation
result = torch.einsum('nkctv,kvw->nctw', x, A)

# Print the shape of the result
print(result.shape)  # Output: torch.Size([1, 20, 8, 3])

torch.Size([1, 20, 8, 3])


In [55]:
result

tensor([[[[ 5.1220e+00,  4.8355e+00,  6.4208e+00],
          [ 5.0591e+00,  3.2090e+00, -1.1434e+01],
          [ 1.2014e-01, -6.7630e+00,  7.9955e-01],
          [-1.3784e+00,  6.6596e-01, -2.7871e+00],
          [-4.2953e+00,  8.3061e+00,  2.6732e+00],
          [ 5.2149e+00,  4.8520e-01, -1.3004e+01],
          [-1.3339e+00, -2.5211e+00,  5.6034e-01],
          [ 2.7685e-01,  1.8114e+00,  4.0560e+00]],

         [[ 8.4307e-01,  6.1201e+00,  6.8873e+00],
          [ 2.2099e+00,  6.9870e+00,  1.2375e+00],
          [-1.5324e+00, -2.0916e+00,  5.8132e-01],
          [ 2.9006e+00, -5.0812e+00, -5.1331e+00],
          [ 1.2874e+00,  2.1019e-01,  8.9793e-01],
          [ 6.3843e+00,  1.8911e-01,  7.3431e+00],
          [-1.8209e+00,  3.3201e+00, -4.4816e+00],
          [ 4.2718e+00, -1.8875e+00,  2.0647e+00]],

         [[-5.7078e+00,  5.1483e+00, -3.8335e+00],
          [-4.0552e+00,  7.5836e+00, -4.2818e+00],
          [-5.1880e+00,  1.4996e+00,  3.4735e+00],
          [ 1.7592e+00, -5.

In [ ]:
class st_gcn(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, feature_size, use_mdn=False, stride=1, dropout=0, residual=True):
        super(st_gcn, self).__init__()

        assert len(kernel_size) == 2
        assert kernel_size[0] % 2 == 1
        padding = ((kernel_size[0] - 1) // 2, 0)
        self.use_mdn = use_mdn
        self.gcn = ConvTemporalGraphical(in_channels, out_channels, kernel_size[1])
        self.feature_layer = nn.Linear(feature_size, out_channels)  # new layer for the feature vector

        # rest of the __init__ method...

    def forward(self, x, A, features):
        res = self.residual(x)
        x, A = self.gcn(x, A)
        features = F.relu(self.feature_layer(features))  # pass the feature vector through the new layer
        x = torch.cat((x, features), dim=1)  # concatenate the feature vector with the output of the gcn layer

        x = self.tcn(x) + res

        if not self.use_mdn:
            x = self.prelu(x)

        return x, A

In [13]:
import torch
feature = torch.rand(128)
feature.shape

torch.Size([128])

In [4]:
# Reshape feature to match the dimensions of x
feature = feature.view(1, 1, -1, 1)

In [5]:
feature.shape

torch.Size([1, 1, 128, 1])

In [29]:
x = torch.randint(800,(1,20, 8, 3))
feature = torch.randint(800,(128,))
feature = feature.view(1, 1, -1, 1)
feature = feature.expand(x.size(0), x.size(1), feature.size(2), x.size(3))
result = torch.cat([x, feature], dim=2)
result.shape

torch.Size([1, 20, 136, 3])

In [17]:
feature = feature.expand(x.size(0), x.size(1), feature.size(2), x.size(3))
feature

tensor([[[[0.6848, 0.6848, 0.6848],
          [0.8411, 0.8411, 0.8411],
          [0.3986, 0.3986, 0.3986],
          ...,
          [0.3444, 0.3444, 0.3444],
          [0.3505, 0.3505, 0.3505],
          [0.0152, 0.0152, 0.0152]],

         [[0.6848, 0.6848, 0.6848],
          [0.8411, 0.8411, 0.8411],
          [0.3986, 0.3986, 0.3986],
          ...,
          [0.3444, 0.3444, 0.3444],
          [0.3505, 0.3505, 0.3505],
          [0.0152, 0.0152, 0.0152]],

         [[0.6848, 0.6848, 0.6848],
          [0.8411, 0.8411, 0.8411],
          [0.3986, 0.3986, 0.3986],
          ...,
          [0.3444, 0.3444, 0.3444],
          [0.3505, 0.3505, 0.3505],
          [0.0152, 0.0152, 0.0152]],

         ...,

         [[0.6848, 0.6848, 0.6848],
          [0.8411, 0.8411, 0.8411],
          [0.3986, 0.3986, 0.3986],
          ...,
          [0.3444, 0.3444, 0.3444],
          [0.3505, 0.3505, 0.3505],
          [0.0152, 0.0152, 0.0152]],

         [[0.6848, 0.6848, 0.6848],
          [0.8411

In [32]:
x[0][0][:,0] 

tensor([146,  64, 462, 111, 605, 569, 562, 260])

In [33]:
feature[0][0][:,0]

tensor([714, 671, 749,  17, 396, 341, 134, 669, 602,  56, 145, 593, 299, 108,
        207,  92, 226, 526, 662, 378, 666, 638,   8,   7, 451, 696, 309,  51,
        496, 237, 148, 470, 411, 511, 415, 368,  96, 656, 340, 412, 342, 289,
        356, 233, 789, 531, 749, 241, 174,  23, 202, 191, 794, 107,  45, 234,
        124, 586,  54, 479, 786, 444, 677, 294, 389, 581, 535, 712, 679, 651,
        160,  49, 660, 467, 446, 748, 746, 481, 144, 609, 295,  61, 371, 327,
        705, 306, 313, 420, 355, 414,  13, 257, 709, 196, 503, 672, 409, 731,
        741, 625, 568, 338, 464, 276,  28, 771, 326, 498, 603, 308, 118, 378,
        751, 698, 727, 173, 702, 295,  47, 653, 219,  26, 790,  79, 332, 380,
        533, 418])

In [34]:
result[0][0][:,0]


tensor([146,  64, 462, 111, 605, 569, 562, 260, 714, 671, 749,  17, 396, 341,
        134, 669, 602,  56, 145, 593, 299, 108, 207,  92, 226, 526, 662, 378,
        666, 638,   8,   7, 451, 696, 309,  51, 496, 237, 148, 470, 411, 511,
        415, 368,  96, 656, 340, 412, 342, 289, 356, 233, 789, 531, 749, 241,
        174,  23, 202, 191, 794, 107,  45, 234, 124, 586,  54, 479, 786, 444,
        677, 294, 389, 581, 535, 712, 679, 651, 160,  49, 660, 467, 446, 748,
        746, 481, 144, 609, 295,  61, 371, 327, 705, 306, 313, 420, 355, 414,
         13, 257, 709, 196, 503, 672, 409, 731, 741, 625, 568, 338, 464, 276,
         28, 771, 326, 498, 603, 308, 118, 378, 751, 698, 727, 173, 702, 295,
         47, 653, 219,  26, 790,  79, 332, 380, 533, 418])

In [2]:
import torch
from torch_geometric.data import Batch
from torch_geometric.data import Data

In [5]:
# Your data
obs_data_forward = torch.tensor([[1, 2, 3], 
                                 [4, 5, 6], 
                                 [7, 8, 9], 
                                 [10, 11, 12], 
                                 [13, 14, 15], 
                                 [16, 17, 18], 
                                 [19, 20, 21], 
                                 [22, 23, 24]], dtype=torch.float)

# Your adjacency matrices
adjacency_matrices = torch.ones((8, 3, 3))

# Convert adjacency matrices to edge_index tensors
edge_indices = [adjacency_matrix.nonzero(as_tuple=False).t() for adjacency_matrix in adjacency_matrices]

# Create a list of Data objects
data_list = [Data(x=obs_data_forward[i].view(1, -1), edge_index=edge_indices[i]) for i in range(8)]

# Create a Batch object from the list of Data objects
batch = Batch.from_data_list(data_list)

print(batch)

DataBatch(x=[8, 3], edge_index=[2, 72], batch=[8], ptr=[9])


In [7]:
import torch.nn.functional as F
from torch_geometric.nn import GATConv
class GAT(torch.nn.Module):
    def __init__(self, input_feature, out_feature, output, heads):
        super().__init__()
        # First GATConv layer. It takes 'input_feature' as input features and returns 'out_feature' as output features.
        # The number of multi-head attentions is 'heads'. Dropout is applied with a rate of 0.6.
        self.conv1 = GATConv(input_feature, out_feature, heads, dropout=0.6)
        
        # Second GATConv layer. It takes 'out_feature * heads' as input features and returns 'output' as output features.
        # The number of multi-head attentions is 1. Dropout is applied with a rate of 0.5.
        self.conv2 = GATConv(out_feature * heads, output, heads=1 , concat=False, dropout=0.5)
        
    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        # Apply the first GATConv layer and activation function (ELU)
        x = F.elu(self.conv1(x, edge_index))
        # Apply dropout
        x = F.dropout(x , p=0.5, training=self.training)
        # Apply the second GATConv layer
        x = self.conv2(x , edge_index)
        # Apply dropout
        x = F.dropout(x , p=0.5, training=self.training)
        # Apply log_softmax and return the result
        return F.log_softmax(x, dim=1)

In [8]:
# Initialize the GAT model
# Assume the input_feature is 3 (as each node has 3 features in obs_data_forward)
# and we want the model to output 2 features for each node.
# We also set the number of heads in the attention mechanism to 4.
model = GAT(input_feature=3, out_feature=64, output=2, heads=4)

# Pass the batch of graphs to the model
output = model(batch)

# Now, 'output' contains the output features of the nodes in the batch of graphs

IndexError: Encountered an index error. Please ensure that all indices in 'edge_index' point to valid indices in the interval [0, 7] (got interval [0, 9])